Build task should actually build the application, not publish
ldtteam/OperaPublicaCreator pull request #13
Opened 2024-08-19 13:59 UTC by Thodor12

Build was implemented completely wrong

2024-08-19 14:27 UTC, marchermans requested changes
This PRs changes are not inline with the goal of the relevant action, that is to build, test and publish its results to github packages so that they are accessible.

2024-08-20 09:27 UTC, marchermans requested changes

2024-08-20 09:35 UTC, Thodor12 commented on .github/workflows/gradle.build.yaml
> +        run: ./gradlew --build-cache ${{ inputs.gradle_tasks }}
We don't actually require version logic for this yet, as this task is just doing an assemble right now

2024-08-23 20:14 UTC, marchermans requested changes

2024-08-23 20:14 UTC, marchermans commented on .github/workflows/gradle.prerelease.yaml
> +          GITHUB_USERNAME: ${{ github.actor }}
Crowdin token is missing.

2024-08-23 20:39 UTC, marchermans approved these changes

2024-08-23 20:39 UTC, merged